application: coe-movie-db-13
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  mime_type: text/css

- url: /static
  static_dir: static
  mime_type: image/jpeg

- url: /static
  static_dir: static
  mime_type: text/javascript

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest